name: libuts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - rioxarray
  - dask
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - shap
  - holoviews
  - hvplot
  - geoviews
  - cartopy
  - panel>=1.8.2
  - plotly
  - geopandas
  - shapely
  - requests
  - pymoo>=0.6.1.5
  - cdo
  - nco
  - jupyterlab
  - notebook
  - pytest
  - pip
  - pip:
      - copernicusmarine
      - mlflow
      - tqdm
      - openpyxl
