name: LiBuTS CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          conda env create -f env/environment.yml || conda env update -f env/environment.yml
          conda activate libuts || source activate libuts
          pip install pytest


      - name: Run vignettes tests
        run: pytest -v vignettes/
