name: LiBuTS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: libuts
          environment-file: env/environment.yml
          python-version: 3.10
          auto-activate-base: false
          channels: conda-forge,defaults

      - name: Verify environment
        run: |
          conda info
          conda list | head -n 15

      - name: Run vignettes tests
        run: pytest -v vignettes/
